### ISSUE TITLE
cluster-role is not required but always assumed

### ISSUE THREAD

**Issue by miguelaferreira** [peymanmortazavi/eks-helm-deploy#4]
I'm trying to use this action to install helm charts. In my setup the AWS keys I'm using already give access to the cluster and no role needs to be assumed. However, when I run the workflow I get the error:
```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::1234567890:user/... is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1234567890:role/blackbox-eks-admin
```

It seems that the role is [always assumed](https://github.com/peymanmortazavi/eks-helm-deploy/blob/master/deploy.sh#L7) irrespectively of it being defined. 

Is there a way to not assume the role, or would that need a PR?

**Comment by AwateAkshay** [comment]
Did you edit configmap `aws-auth` to add role ? @miguelaferreira

**Comment by miguelaferreira** [comment]
No I did not add or even configure any role for the action. The credentials I provide are enough and no role needs to be assumed.

**Comment by AwateAkshay** [comment]
can you add role in `aws-auth` configmap ? and try ?

**Comment by miguelaferreira** [comment]
Not really. That's now how I want to have the access set up.

**Comment by AwateAkshay** [comment]
I did add `cluster-role-arn` and it worked for me @miguelaferreira
