### ISSUE TITLE
Can we please to publish a new release?

### ISSUE THREAD

**Issue by yunpengeric** [peymanmortazavi/eks-helm-deploy#6]
Hi @peymanmortazavi 

Can we please to publish a new release to include the new features? 

Thanks
Eric

**Comment by miguelaferreira** [comment]
It's not even possible to run the action from master since the referenced container image does not exist.
https://github.com/peymanmortazavi/eks-helm-deploy/blob/master/action.yml#L53
```yaml
image: 'docker://peymanmo/eks-helm-deploy:latest'
```

**Comment by miguelaferreira** [comment]
@Hassnain-Alvi I've been using a forked action while waiting for this work to be releasesed.

```
- uses: miguelaferreira/eks-helm-deploy@optional-role
```

**Comment by AwateAkshay** [comment]
I moved to https://github.com/craftech-io

[eks-helm-deploy-action](https://github.com/craftech-io/eks-helm-deploy-action)

**Comment by peymanmortazavi** [comment]
Hi everyone, I've been off of GitHub for quite some time. I did not really think anyone would use this package, I'll be working on addressing the issues that have ben raised and also to improve the documentation.

**Comment by AwateAkshay** [comment]
@peymanmortazavi please can you release new version?

**Comment by peymanmortazavi** [comment]
@AwateAkshay I deployed the new version. Sorry for the delay everyone.
