### ISSUE TITLE
Request collaborators access

### ISSUE THREAD

**Issue by yunpengeric** [peymanmortazavi/eks-helm-deploy#8]
HI @peymanmortazavi 

Do you mind giving me collaborators access? I am happy to maintain it. 

Thanks
Eric

**Comment by peymanmortazavi** [comment]
Hey Eric (@yunpengeric),

Absolutely, thanks for opting for this. I've been suuuper slow in responding to people with other commitments so your help would be more than welcome. I just sent you an invite.

Best,
Peyman
